spring:
  application:
    name: zipkin
  rabbitmq:
    host: 192.168.56.102
    username: root
    password: root

server:
  port: 9411

security:
  user:
    name: admin
    password: ${ZIPKIN_SERVER_PASSWORD:admin}
